all:
  children:
    jump:
      hosts:
        jump1:
          ansible_host: 5.75.227.88
          ansible_user: yornik
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          loki_hostname: loki.homelab.internal
        jump2:
          ansible_host: 152.53.107.155
          ansible_user: yornik
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
          loki_hostname: loki.homelab.internal
