---

- name: Create application directory
  file:
    path: /opt/{{ compose_project }}
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Deploy docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: /opt/{{ compose_project }}/docker-compose.yml
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Deploy systemd service unit file
  template:
    src: docker-compose@.service.j2
    dest: /etc/systemd/system/docker-compose@{{ compose_project }}.service
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Reload systemd daemon
  command: systemctl daemon-reload
  become: true

- name: Enable and start Docker Compose service
  systemd:
    name: docker-compose@{{ compose_project }}
    enabled: true
    state: started
  become: true

