---
- name: Reload systemd
  command: systemctl daemon-reexec
- name: Restart Caddy
  systemd:
    name: caddy
    state: restarted
- name: Reload Caddy
  systemd:
    name: caddy
    state: reloaded
- name: Restart fail2ban
  service:
    name: fail2ban
    state: restarted

