- name: Configure Jump Hosts
  hosts: jump1:jump2
  become: true
  roles:
    - role: common
    - role: caddy
    - role: headscale
      when: inventory_hostname == "jump1"
    - role: headscale-admin
      when: inventory_hostname == "jump1"
    - role: powerdns
    - role: powerdns-admin
      when: inventory_hostname == "jump1"
    - role: tailscale
    - role: node-exporter
    - role: promtail

